### ISSUE TITLE
Create Order History Page for Specific User

### ISSUE THREAD

**Issue by kolawoletech** [Marketcloud/ionic-marketcloud#1]
How can I implement an order history page for a specific user? What is that implemented in the API?

**Comment by fatmatto** [comment]
You can just use the [JS sdk](https://github.com/Marketcloud/marketcloud-js) in the following way
```javascript
client.orders.list()
.then( response => {
// response contains your orders
})
```

Just be sure that the user has logged with 
```javascript
client.users.authenticate(myUsername, myPassword)
```

before retrieving the list of orders

**Comment by kolawoletech** [comment]
Will give it a try
